### ISSUE TITLE
Cannot Read property verbose of undefined

### ISSUE THREAD

**Issue by davidearlotto** [arifsetiawan/flatten#9]
Hi arifsetiawan, 
using your module, in the flatten.js file. The error is shown in the title. It's called when the code request:

options.verbose

Because there is no options defined. Where am I wrong?
I'm using the module because is require in the node-zendesk module.
Thanks!

**Comment by arifsetiawan** [comment]
Hi @davidearlotto, 
Sorry for late reply, I hope you already resolve your issue. [node-zendesk](https://github.com/blakmatrix/node-zendesk) is not using my `flatten-packages` module but this [flatten](https://github.com/jfhbrook/node-flatten). You can check from node-zendesk package.json
